// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from webkit-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "WebKitContextMenuAction", sizeof(WebKitContextMenuAction), alignof(WebKitContextMenuAction));
    printf("%s;%zu;%zu\n", "WebKitContextMenuClass", sizeof(WebKitContextMenuClass), alignof(WebKitContextMenuClass));
    printf("%s;%zu;%zu\n", "WebKitContextMenuItemClass", sizeof(WebKitContextMenuItemClass), alignof(WebKitContextMenuItemClass));
    printf("%s;%zu;%zu\n", "WebKitFrameClass", sizeof(WebKitFrameClass), alignof(WebKitFrameClass));
    printf("%s;%zu;%zu\n", "WebKitHitTestResultClass", sizeof(WebKitHitTestResultClass), alignof(WebKitHitTestResultClass));
    printf("%s;%zu;%zu\n", "WebKitHitTestResultContext", sizeof(WebKitHitTestResultContext), alignof(WebKitHitTestResultContext));
    printf("%s;%zu;%zu\n", "WebKitScriptWorldClass", sizeof(WebKitScriptWorldClass), alignof(WebKitScriptWorldClass));
    printf("%s;%zu;%zu\n", "WebKitURIRequestClass", sizeof(WebKitURIRequestClass), alignof(WebKitURIRequestClass));
    printf("%s;%zu;%zu\n", "WebKitURIResponseClass", sizeof(WebKitURIResponseClass), alignof(WebKitURIResponseClass));
    printf("%s;%zu;%zu\n", "WebKitUserMessageClass", sizeof(WebKitUserMessageClass), alignof(WebKitUserMessageClass));
    printf("%s;%zu;%zu\n", "WebKitUserMessageError", sizeof(WebKitUserMessageError), alignof(WebKitUserMessageError));
    printf("%s;%zu;%zu\n", "WebKitWebEditorClass", sizeof(WebKitWebEditorClass), alignof(WebKitWebEditorClass));
    printf("%s;%zu;%zu\n", "WebKitWebFormManager", sizeof(WebKitWebFormManager), alignof(WebKitWebFormManager));
    printf("%s;%zu;%zu\n", "WebKitWebFormManagerClass", sizeof(WebKitWebFormManagerClass), alignof(WebKitWebFormManagerClass));
    printf("%s;%zu;%zu\n", "WebKitWebHitTestResultClass", sizeof(WebKitWebHitTestResultClass), alignof(WebKitWebHitTestResultClass));
    printf("%s;%zu;%zu\n", "WebKitWebPageClass", sizeof(WebKitWebPageClass), alignof(WebKitWebPageClass));
    printf("%s;%zu;%zu\n", "WebKitWebProcessExtensionClass", sizeof(WebKitWebProcessExtensionClass), alignof(WebKitWebProcessExtensionClass));
    return 0;
}
