// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from webkit-gir-files
// DO NOT EDIT

mod context_menu;
pub use self::context_menu::ContextMenu;

mod context_menu_item;
pub use self::context_menu_item::ContextMenuItem;

mod frame;
pub use self::frame::Frame;

mod hit_test_result;
pub use self::hit_test_result::HitTestResult;

mod script_world;
pub use self::script_world::ScriptWorld;

mod uri_request;
pub use self::uri_request::URIRequest;

mod uri_response;
pub use self::uri_response::URIResponse;

mod user_message;
pub use self::user_message::UserMessage;

mod web_editor;
pub use self::web_editor::WebEditor;

mod web_form_manager;
pub use self::web_form_manager::WebFormManager;

mod web_hit_test_result;
pub use self::web_hit_test_result::WebHitTestResult;

mod web_page;
pub use self::web_page::WebPage;

mod web_process_extension;
pub use self::web_process_extension::WebProcessExtension;

mod enums;
pub use self::enums::ContextMenuAction;
pub use self::enums::UserMessageError;

mod flags;
pub use self::flags::HitTestResultContext;

#[doc(hidden)]
pub mod traits {
    pub use super::web_form_manager::WebFormManagerExt;
}
